### ISSUE TITLE
Scale isn't working correctly.

### ISSUE THREAD

**Issue by michalbe** [michalbe/cervus#30]
Scale setter isn't working correctly, it's scaling `by` the vector, not `to` the vector.
### Repro
 - set entitie's scale `[5, 5, 5]`
 - scale it down to the initial size with `entity.scale = [1, 1, 1];`
 - not that nothing happened, because `entity.local_matrix` was just scaled by `[1, 1, 1]` vector.

**Comment by michalbe** [comment]
@stasm could you take a look at this one pls?

**Comment by stasm** [comment]
Ha, good catch! I'm on it.
