### ISSUE TITLE
Remove Entity.origin

### ISSUE THREAD

**Issue by stasm** [michalbe/cervus#35]
Previous discussion: https://github.com/michalbe/cervus/pull/23#discussion_r135329139

By removing `Entity.origin` we can keep the API surface small. The same effect can be achieved by introducing an intermediate parent in the object hierarchy. This solution also has the benefit of being consistent: rotating ancestors results in consistent rotation of all descendants relative to the ancestor's origin.  With `Entity.origin` it's weird that rotating the entity may not happen around it's (0, 0, 0) point.

**Comment by stasm** [comment]
Sorry, in a bit of a rush and I'm not sure I'm explaining this right.  What I mean is that with intermediate parents we have a consistent rule: rotating an entity always rotates around its (0, 0, 0).  When a parent is rotated, world-rotation of children is also updated relative to the parent. It's surprising to expect that children will additionally rotate around their respective `origins` in that case.

**Comment by michalbe** [comment]
As stated before, I'm against removing the origin. It will be harder to achieve same thing using parent `Entity`, it introduces additional level of abstraction, and the profit isn't really there. Big players are doing the same thing - for instance:
  -  in Unreal it's called `Pivot translation`:
![screen shot 2017-08-27 at 00 26 18](https://user-images.githubusercontent.com/347657/29745931-2ef6d7b6-8ac9-11e7-8c4c-08bd514d80d0.png)
  - in CryEngine it's `Pivot Point`:
![screen shot 2017-08-27 at 01 47 13](https://user-images.githubusercontent.com/347657/29745954-c488567e-8ac9-11e7-9c78-3648b364a802.png)
  - and Unity have a [thread](http://answers.unity3d.com/questions/7664/changing-the-pivot-point-of-meshes.html) with plenty of `unfortunately, it's not supported by the editor and you need to use a workaround with parent game object` posts :).

**Comment by michalbe** [comment]
Since #37 is removing the origin from the `Entity` class, let's rename this issue so we'll remember to add it later.
